spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 3ub8qsc17e3cahpefuqt3oifla
            client-secret: 1vqojafoos9el67br1punb9g049e89dcllhmr1i0smedv07gbspp
            redirect-uri: http://challenge-env.eba-s2sqww3q.us-east-2.elasticbeanstalk.com/login/oauth2/code/cognito
        provider:
          cognito:
            issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_BqoZK3xsB
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://challenge.c5asyu8iwxqc.us-east-2.rds.amazonaws.com:5432/facchindb
    docker:
      enabled : false

